name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  API: ${{ secrets.API }}
  API_SECRET: ${{ secrets.API_SECRET }}
  BEARER: ${{ secrets.BEARER }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build
      run: cargo build --verbose
      
    - name: Test
      run: cargo test --verbose
